apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: generator
  name: pass-app
spec:
  selector:
    matchLabels:
      app: pass-app
  template:
    metadata:
      labels:
        app: pass-app
    spec:
      containers:
      - name: pass-app
        image: wesleip/app_password:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: generator
  name: pass-app
spec:
  type: ClusterIP
  selector:
    app: pass-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: generator
  name: pass-app
spec:
  ingressClassName: nginx
  rules:
  - host: "password.com.br"
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
        service:
          name: pass-app
          port:
            number: 80