apiVersion: v1
kind: Namespace
metadata:
  name: generator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pass-app
  namespace: generator
spec:
  project: default
  source:
    repoURL: https://github.com/hubpagec/argocd-teste.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://172.18.0.3:6443'
    namespace: generator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true