apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pass-app
  namespace: generator
spec:
  project: default
  source:
    repoURL: https://github.com/hubpagec/argocd-teste.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://172.18.0.3:6443'
    namespace: generator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---
piVersion: apps/v1
kind: Deployment
metadata:
  namespace: generator
  name: pass-app
spec:
  selector:
    matchLabels:
      app: pass-app
  template:
    metadata:
      labels:
        app: pass-app
    spec:
      containers:
      - name: pass-app
        image: wesleip/app_password:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: generator
  name: pass-app
spec:
  type: ClusterIP
  selector:
    app: pass-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: generator
  name: pass-app
spec:
  ingressClassName: nginx
  rules:
  - host: "password.com.br"
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
        service:
          name: pass-app
          port:
            number: 80